### ISSUE TITLE
Zipper Initiative not zippering

### ISSUE THREAD

**Issue by borbsauce** [caewok/fvtt-zipper-initiative#7]
Hey folks! A week or two ago my game decided to switch over to using zipper initiative. When we tested this module it worked exactly as intended! That said, last night, when we went to do some combat, it was not zippering as previously. We like to alternate between players and enemies, but for some reason, it was consistently stacking all the players and THEN all the enemies, which it was not previously doing. What have I done wrong here?

**Comment by borbsauce** [comment]
I just ran Find the Culprit with the prerequisites and Zipper Initiative still running and it's still not zippering.

**Comment by borbsauce** [comment]
I did buy the new Dungeon Master's Guide module in-between. Not sure if that would effect this.

**Comment by caewok** [comment]
Do you see any errors in the browser console (usually F12 to make the console appear)? Specifically when you are rolling initiative?

Appears to work for me when I test it using Foundry v12.331 and dnd5e v4.1.2. But I don't have the Dungeon Master's Guide module. If you disable that and all other modules except Zipper and libWrapper, does it still not sort correctly?

**Comment by SabreRunner** [comment]
I'm seeing this when I roll all. Does it have something to do with it?
I also see no config or controls for it. Shouldn't there be?
Foundry v12.331, PF2e v6.11.1

`Foundry VTT | Error thrown in hooked function 'displayChancesModifiersDialog' for hook 'renderCheckModifiersDialog'

Error: Error thrown in hooked function 'displayChancesModifiersDialog' for hook 'renderCheckModifiersDialog'. Cannot read properties of null (reading 'value')
[Detected 1 package: pf2e-chances(1.3.2)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at CheckModifiersDialog._callHooks (foundry.js:5918:13)
    at CheckModifiersDialog._render (foundry.js:5879:10)`

**Comment by SabreRunner** [comment]
@caewok ?

**Comment by dsakura** [comment]
Same with me. Using Foundry v12.343, dnd 4.4.3. 
Does the module still receive maintenance? Did anyone find any fix? Thanks! This module is great!

**Comment by SabreRunner** [comment]
I eventually switched to Lancer Initiative. Works pretty well.

**Comment by dsakura** [comment]
> I eventually switched to Lancer Initiative. Works pretty well.

But lancer inititive is only popcorn right? I prefer to interspersed the initiative and have the initiative of the leader. The popcorn option I don't use.

**Comment by SabreRunner** [comment]
We roll initiative. Highest goes first, then we go back and forth. Perfect Zipper.

**Comment by dsakura** [comment]
> We roll initiative. Highest goes first, then we go back and forth. Perfect Zipper.

I understood, uses popcorn but alternating between allied and enemies sides. I will test, but I also hope that this module, very practical. Thanks

**Comment by SabreRunner** [comment]
I was also unsure about it but a veteran player of mine told me to try it and it seems to fulfill the need quite well.

**Comment by caewok** [comment]
Yes, I will be updating it. Sorry for the wait.

**Comment by dsakura** [comment]
> Yes, I will be updating it. Sorry for the wait.

oh perfect! many thanks

**Comment by caewok** [comment]
I pushed some updates for v12 and also pushed a v13 release. If you are still having problems, please submit a new issue. Thanks all for the comments!
